### ISSUE TITLE
Is there a way to call TcpStream::connect in NonBlocking mode?

### ISSUE THREAD

**Issue by hoxnox** [carllerche/mio#164] opened 2015-05-08 11:11 UTC
I have looked through the sources and didn't find a way to create asynchronous TCP client. I missed something or I can't make connect in nonblocking mode?

**Comment by carllerche** [comment] 2015-05-10 00:39
Sorry, it's a bit confusing at the moment. This is improved on master. Assuming you are using what is on [crates.io](https://crates.io), you can create a `TcpSocket` using `mio::tcp::v4()`. This will be set to non-blocking mode by default. You can then call connect on it.

On master, this is changed to just be: `mio::tcp::TcpStream::connect(...)` which will connect in non-blocking mode by default.

Closing the issue for now, but feel free to re-open it (or create new ones).

**Closed by carllerche** 2015-05-10 00:39 UTC

**Comment by hoxnox** [comment] 2015-05-10 05:12
Thanks for help and your work in general.

**Comment by hoxnox** [comment] 2015-05-14 06:53
In the example below writable is never called, but connection established. What I'm doing wrong?

    extern crate mio;
    use std::net;
    
    struct Hnd {
        stream: Option<mio::NonBlock<net::TcpStream>>
    }
    
    impl Hnd {
        fn new() -> Hnd {
            Hnd {
                stream: None
            }
        }
    }
    
    impl mio::Handler for Hnd {
        type Timeout = u32;
        type Message = ();
    
        fn timeout(&mut self, event_loop: &mut mio::EventLoop<Self>, timeout: u32) {
            println!("Timeout.");
            if timeout == 0 {
                event_loop.timeout_ms(0, 1000).unwrap();
            }
            if !self.stream.is_some() {
                let sock = mio::tcp::v4().unwrap();
                let google = net::Ipv4Addr::new(173, 194, 122, 224);
                let (stream, _) = sock.connect(&net::SocketAddr::V4(net::SocketAddrV4::new(google, 80))).unwrap();
                event_loop.register(&stream, mio::Token(0)).unwrap();
                self.stream = Some(stream);
            }
        }
    
        fn writable(&mut self, _: &mut mio::EventLoop<Self>, token: mio::Token) {
            println!("Writable token {}.", token.as_usize());
        }
    }
    
    fn main() {
        let mut h = Hnd::new();
        let mut event_loop: mio::EventLoop<Hnd> = mio::EventLoop::new().unwrap();
        event_loop.timeout_ms(0, 1000).unwrap();
        event_loop.run(&mut h).unwrap();
    }

**Comment by dwrensha** [comment] 2015-05-14 13:35
I think the problem is that this line only registers readable interest:

```rust
        event_loop.register(&stream, mio::Token(0)).unwrap();
```

If you change it to the following, it should work as you expect:

```rust
        event_loop.register_opt(&stream, mio::Token(0), mio::Interest::writable(), mio::PollOpt::edge()).unwrap();
```

**Comment by hoxnox** [comment] 2015-05-14 15:02
Yes, it works. Thanks.
It's not clear without documentation.

**Comment by carllerche** [comment] 2015-05-14 16:38
@dwrensha you are right, I wonder why it only registers readable... it probably should register interest in everything.

@hoxnox I would greatly appreciate doc PRs :)

**Comment by hoxnox** [comment] 2015-05-14 16:50
@carllerche My English is not so good, but I'll try to find some time next week to write several examples.
