### ISSUE TITLE
TcpStream etc should implement Clone

### ISSUE THREAD

**Issue by cmr** [carllerche/mio#224] opened 2015-08-03 03:27 UTC
At least, I think they should. Any fundamental issue with this? (I haven't looked into a patch yet)

**Comment by carllerche** [comment] 2015-08-03 17:25
They probably should implement `dup() -> io::Result<TcpStream>`. There may be utility in having a `Dup` trait.

**Comment by cmr** [comment] 2015-08-03 17:26
I mean a copy of the same fd, not a new fd, but `dup` is probably also useful.

**Comment by carllerche** [comment] 2015-08-03 17:27
The problem w/ returning a new `TcpStream` w/ the same FD is that the FD is dropped when `TcpStream` goes out of scope. So, the cloned `TcpStream` would become invalid when the original value is dropped and vice versa

**Comment by ayosec** [comment] 2015-08-04 02:53
@cmr Out of curiosity, why do you need to clone the `TcpStream`?

**Comment by cmr** [comment] 2015-08-04 03:20
@ayosec shenanigans with rust-openssl that I hope to fix (https://github.com/sfackler/rust-openssl/issues/250)

**Comment by carllerche** [comment] 2015-08-20 23:25
I don't think that `TcpStream` can implement clone. I read the issue, and it seems that the problem is that `SslStream` does not implement `Evented`.

My general understanding of SSL & non-blocking sockets is that it is better to use the in memory buffer BIO (w/ OpenSSL) which completely decouples sockets from SSL.

So, either the SSL lib would need to implement `Evented` on `SslStream` (probably not a great idea), or there would need to be a custom `SslStream` wrapper that implements `Evented` given that implementing clone on 

Also, this issue seems related to #226. So, I think I'm going to close this in favor of that one since implementing `Clone` for `TcpStream` is not possible.

**Closed by carllerche** 2015-08-20 23:25 UTC
