### ISSUE TITLE
`set_nodelay` taking a bool is anti-patern "boolean trap".

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#214] opened 2015-07-12 07:16 UTC
Can it be reconsidered to be made two functions, or at least named `switch_nodelay`?

**Comment by carllerche** [comment] 2015-07-13 19:27
While I don't necessarily disagree w/ the "boolean trap" argument, the flip side is that they mirror the sockopt API.

Anyway, I'm open to a new name, but am not in love w/ `switch_nodelay`

**Comment by dpc** [comment] 2015-07-13 20:09
`enable_nodelay` / `disable_nodelay`? Easy to read. Donno, maybe `mio` being so low-level can live `set_nodelay` taking a bool. I've just hit this problem myself, and it immediately rang a bell in my head that this is a typical "boolean trap". Especially with "no-" it's just mental effort to parse.

**Comment by rrichardson** [comment] 2015-12-07 03:55
The problem is that nodelay is one of a half dozen commonly used sockopts.  

Rather than having a dozen enable/disable functions,  I would prefer an exensible, rustic socket options interface.  

E.g. A set of standard enums for IP, UDP, and TCP (e.g.TCP_NODELAY and TCP_REUSEADDR, etc)  and some way to inject inject new flag values for odd platforms or experimental flags. 

maybe a Sockopt trait which has a single method; value?   I dunno.

**Comment by carllerche** [comment] 2015-12-14 15:54
@rrichardson I would say that the specific opts exposed via functions like `set_nodelay` should be limited to those that are portable. The full gamut will have to be exposed via platform specific extensions... A `Sockopt` trait is more appropriate in this case.

I'm going to close this as a "won't fix" Perhaps the current API is unfortunate, but it is the pattern adopted with net2: https://doc.rust-lang.org/net2-rs/net2/trait.TcpStreamExt.html

**Closed by carllerche** 2015-12-14 15:54 UTC
Labels: api, waiting
