### ISSUE TITLE
Panic when Registration is dropped from non-main thread

### ISSUE THREAD

**Issue by svyatonik** [carllerche/mio#532] opened 2017-01-31 12:14 UTC
We have a project, which uses mio + tokio-core + futures + futures-cpupool to implement some network protocol (basically - sending and responding to messages). Everything works fine, but on rare occasion (too rare actually -it is a big problem to reproduce it), our main thread (which polls tokio-core event loop) panics with next stack (it is about v0.6.4, but on latest master issue remains):
```
  10:     0x5579b378c5af - mio::poll::Poll::poll::hc960007ac1ed502f
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
                        at /home/svyatonik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:816
                        at /home/svyatonik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:744
                        at /home/svyatonik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:654
                        at /home/svyatonik/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.4/src/poll.rs:251
  11:     0x5579b37863df - tokio_core::reactor::Core::poll::h43f4b499158d6eeb
                        at /home/svyatonik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:272
```

So this unwrap leads to panic:
https://github.com/carllerche/mio/blob/master/src/poll.rs#L816
Giving that `head` in this `unlink` method is actually `ReadinessQueueInner::head_all_nodes`, I have examined `poll.rs` to find how it is changed. Here I have found one suspicious method.  `head_all_nodes` is set to `None` here:
https://github.com/carllerche/mio/blob/master/src/poll.rs#L702
And it only filled back with `Some` couple of lines above:
https://github.com/carllerche/mio/blob/master/src/poll.rs#L710

I have a test for this situation in this commit:
https://github.com/svyatonik/mio/commit/58e535e6081573db98b546247f3af6c1c1f0b974
If you'll run it with `reset && cargo test -- drop_registration_from_non_main_thread`, it will fail eventually.

But I'm still not sure - if that's a `RegistrationQueue` issue, or is it improper usage? Is it OK to drop `Registration`-s from cpupool threads, or not?
If it is not OK, then I will probably move this issue to `futures-rs`, because sometimes it is actually dropped from other threads - I have reproduced it while debugging. Drop is starting here:
https://github.com/alexcrichton/futures-rs/blob/futures-cpupool-0.1.2/futures-cpupool/src/lib.rs#L267

**Comment by svyatonik** [comment] 2017-02-01 09:01
There's a chance that the situation is opposite - `drop` occurs in main thread && new `Registration` is created in one of cpupool threads. But that single time I have got this situation in gdb was just after the `drop` from cpupool thread.

**Comment by carllerche** [comment] 2017-02-02 23:01
Seems bad! I will investigate.

**Comment by carllerche** [comment] 2017-02-02 23:22
Alright, the panic happens locally. I'm going to dig in now :)

**Comment by carllerche** [comment] 2017-02-03 21:49
I have a solid hunch as to what the issue is, that being said even the test case takes a while (an hour) to trigger... so it is hard to be sure.

**Comment by carllerche** [comment] 2017-02-25 06:03
This should be fixed on master.

**Closed by carllerche** 2017-02-25 06:03 UTC
