### ISSUE TITLE
mio doesn't support FreeBSD 12

### ISSUE THREAD

**Issue by Crest** [carllerche/mio#819] opened 2018-02-14 14:44 UTC
FreeBSD 12 extended struct kevent with four extra 64bit parameters (two for the filter and two for the userspace application). This change breaks mio on FreeBSD 12-CURRENT.

**Comment by asomers** [comment] 2018-02-14 15:42
This issue is actually in libc, not mio.  libc lacks a way to deal with backwards-compatible but forwards-incompatible changes to an operating system's C libraries (other than adding new interfaces in later versions).  The situation is even worse in OpenBSD, which can have backwards-incompatible changes.  However, the FreeBSD ports tree contains patches for libc to make it work in 12.  So if you install Rust through ports instead of through Rustup, then you should be ok.
https://github.com/rust-lang/libc/issues/570

**Comment by carllerche** [comment] 2018-02-14 17:22
Thanks for the clarification. Given that the issue is in `libc`, i'm going to close this under the assumption that when it is fixed upstream, Mio will work.

**Closed by carllerche** 2018-02-14 17:22 UTC
