### ISSUE TITLE
Weird behavior on reusing tokens.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#172] opened 2015-05-18 02:44 UTC
Is token reuse supported? It does not work for me, and I wonder if I'm doing something wrong.

I've implemented a test echo server, which is basically modified echo unix test, in which I'm reusing Tokens.

https://github.com/dpc/mioecho

Everything seems OK most of the time, but after I run:

```
wrk --timeout 2s http://localhost:18080
```

The server go nuts.

After connecting with telnet, I can see that socket returned to handler is  different than the one `netstat -p -n` is indicated I'm connecting from.

The read returns 41 bytes, just like `wrk` handing, also on write the socket seems already disconnected: 

```
RUST_LOG=miotest=debug cargo  run
(...)
DEBUG:miotest: Token(1) - new token
DEBUG:miotest: Some(Token(1)), 0x7f816334f010, Ok(V4(127.0.0.1:50114)): new connection
DEBUG:miotest: Some(Token(1)), 0x7f816334f010, Ok(V4(127.0.0.1:50114)): read 41 bytes!
DEBUG:miotest: Some(Token(1)), 0x7f816334f010, Err(Error { repr: Os(107) }): wrote 41 bytes!
DEBUG:miotest: Some(Token(1)), 0x7f816334f010, Err(Error { repr: Os(107) }) deregister
DEBUG:miotest: Dropping Some(Token(1)), 0x7f816334f010, Err(Error { repr: Os(107) })
```

**Comment by dpc** [comment] 2015-05-20 01:43
Hello? :)

**Comment by carllerche** [comment] 2015-05-20 03:14
Hey, sorry for the delay. Could you tell me if you are running on OS X or on Linux? I'm trying to reproduce the issue.

**Comment by zonyitoo** [comment] 2015-05-20 03:38
Actually I have encountered some weird behaviors like this, but I am not sure who to blame, `kqueue` or `Slab`.

**Comment by carllerche** [comment] 2015-05-20 04:31
I haven't been able to reproduce anything that seemed strange. Could you add some assertions to mioecho and try to get me steps to hit them?

**Comment by carllerche** [comment] 2015-05-20 04:32
I assume it would be possible for the event loop to return previously used tokens if the socket has not been fully shutdown and is still in use.

**Comment by zonyitoo** [comment] 2015-05-20 05:39
If try to `deregister` the fd after handling the event, then on the next time, readable and writable events with `Token(0)` will be notified by mio.

Kqueue, OS X 10.10.4.

I am sure that I haven't set the `PollOpt::oneshot()`. Still wondering why, maybe kqueue is the one to blame.

**Comment by rrichardson** [comment] 2015-05-20 13:47
I'm not sure if there if there is more than one root cause, but you're re-registering potentially disconnected sockets with this logic here:  https://github.com/dpc/mioecho/blob/master/src/main.rs#L70-L79  
If there is data in the buffer then you don't deregister the socket, in fact, you re-register it, however, the OS is going to hand that FD to a new connection, and you'll end up handling that fd twice.  This has different behavior on epoll vs kqueue. 

I'd recommend ignoring the data in the buffer and always deregistering on hangup. For this particluar example, there is no way you'll be able to echo the data back to the client, because they hung up.   In more general applications, if you need the data, just copy the data out before destroying (or reusing) the connection.

**Comment by dpc** [comment] 2015-05-21 01:30
@carllerche : I'm running on Linux. And yes, from my perspective it looks like a Token is returned with old associated socket.

@zonyitoo: I have investigated slab (as it's sitting right there, and is not complicated, and it seemed OK to me).

@rrichardson: "however, the OS is going to hand that FD to a new connection, "

I need to fully analyze what you've wrote, but AFAIK at least TCP has a FIN state for both communication directions. Peer can "disconnect the sending direction", while still handling the receiving. Documentation of MIO does not specify what the "hup" event really means, so I assumed that it's a "peer won't send us anything anymore" and "read" and "write" failure will give me more explicit information . I'll test this more.

**Comment by dpc** [comment] 2015-05-21 05:30
While testing @rrichardson suggestion I've managed to panic in the slab:

https://github.com/dpc/mioecho/commit/5fc54539db3bce4a73a5790efb40a3af81ec5a86

**Comment by dpc** [comment] 2015-05-21 06:03
Could it be this:

https://lwn.net/Articles/520012/

"It is not currently possible to reliably delete epoll items when using the same epoll set from multiple threads. After calling epoll_ctl with EPOLL_CTL_DEL, another thread might still be executing code related to an event for that epoll item (in response to epoll_wait). Therefore the deleting thread does not know when it is safe to delete resources pertaining to the associated epoll item because another thread might be using those resources. "

?

**Comment by rrichardson** [comment] 2015-05-21 11:49
It's this:
https://github.com/carllerche/mio/blob/master/src/event_loop.rs#L299-L305

It looks like your disconnect code and de-register code is mostly correct,
however,  Mio  checks readable events and issues callbacks, then writable
events, one after another in the same function after polling.  So if you
get a HUP message in readable, and the socket is also writable (which if
you're doing edge + oneshot it most certainly will be)  then what happened
is you disconnected the socket and removed it,  then your writable handler
tried to reference that socket in the slab with :
https://github.com/dpc/mioecho/blob/break/src/main.rs#L189

So you have two options, 1, store information that the socket is closing
instead of removing the socket from conns right away.  This is tricky. I'd
probably just recommend option 2; use slab::get(Token) which returns
Option<T>  then you can fetch the socket if it exists, or do nothing if it
doesn't.   The downside is that you might be ignoring legitimate errors,
but it seems unlikely that this scenario could occur in any other way.

**Comment by dpc** [comment] 2015-05-21 19:17
@rrichardson : Oh, interesting. Thank you. But just to make clear: this is another issue. I need to double check, but I don't think this is my original root problem.

Second, it seems to me that it would be better if mio just reversed the order. Rationale:

* If a peer is both readable and writable, then handling a write to peer first seems better. Readable data are already here, while what we are to write needs time to reach the peer, also in case like my echo server when recv and send share the common buffer, if I first send the data, then I have more free space for receiving.
* Another reason is corectness. After handling HUP and deregistering, I would not expected a writable event again. Reversing the write / read handling order seem to fix it right away.

**Comment by dpc** [comment] 2015-05-22 05:06
OK, I think I've found it. I've just need to `accept` in loop:

https://github.com/dpc/mioecho/commit/8786be8b9c917203150f1d0aa5b4546aa21e2799#diff-639fbc4ef05b315af92b4d836c31b023R155

**Comment by rrichardson** [comment] 2015-05-22 11:57
Right. Good catch. If you're edge+oneshot polling then you definitely need
to clean out the socket, the other thing you can do is just reregister the
listener for Read after every accept.  But accepting in a loop is probably
the better approach as long as you don't get so many incoming connections
that it starves the rest of the event handlers.

**Comment by dpc** [comment] 2015-05-25 00:07
BTW.`mioecho` is quite ready. I'm getting decent performance (a little bit less than simpler libev server), so quite well.

If you have a place where I could link to it, as an simple example of `mio`-based project, I would be happy to add it there.

If you have any idea how to optimize the performance, I would be happy to hear it. `perf` tells me that `Connection::reregister` is place to optimize code-wise. Due to this issue, I'm using a bit more complicated "hup" handling than initially. Also, my connection handling is a bit more complicated, as I'm planing to toy with it to add cooroutines and 'nom' parsing to explore more sophisticated server logic.

**Comment by rrichardson** [comment] 2015-05-25 10:52
If you want, you can try to remove one-shot events, so you don't have the
overhead of reregistering at each event.  That overhead is pretty
negligible in the grand scheme of things, e.g. with larger messages and
parsing, etc.  You might want to try changing it to level triggered with no
one-shot, it should just work. If you keep it at edge-triggered without
one-shot, you'll need to ensure that you always clear out the socket
buffers on read events, and always re-register for writes no matter what.

**Comment by carllerche** [comment] 2015-05-27 20:19
@rrichardson Do you think there any things that need to change in mio based on this thread?

@dpc There hasn't been much work on optimizing mio yet besides trying to avoid doing anything stupid :). The fact that it is only slightly slower than libev is promising. I haven't even looked at any perf output yet, but if you have any insight, let me know

I'm assuming that you are running the build artifacts from `cargo build --release` (so that it gets properly optimized). There is the possibility that some things aren't getting inlined well, etc...

**Comment by rrichardson** [comment] 2015-05-27 23:32
@carllerche - based on this thread, no.

**Comment by carllerche** [comment] 2015-05-28 01:08
@dpc I going to close this issue. Feel free to open new ones if you discover anything else.

**Closed by carllerche** 2015-05-28 01:08 UTC
