### ISSUE TITLE
Mio memory usage - 2.5mb+ for running loop

### ISSUE THREAD

**Issue by tigranbs** [carllerche/mio#427] opened 2016-07-15 09:23 UTC
Hi I'm doing integrated library using Mio loop and after having some working demo, I've been surprised about memory usage just for running loop, it's around `2.5mb`. The good thing is that it's not growing fast during data transfer, but for my usecase it's really huge.

Main problem with my application is that I've created integratabtle async database, and I'm running event loops based on current CPU cores, so if server have 12 cores then only program initialization is getting `12*2.5 = 30mb` RAM memory. 

What can I do with this ?

P.S.  I've done some initial research for using `libuv` and found that it is very very cheap in terms of memory usage compared to Mio. Is there any downsides to using `libuv` (Performance or anything else) ?

**Comment by sateffen** [comment] 2016-07-15 10:28
What operating system are you on? On windows I've got some memory problems as well (implementation is pretty new), but on a linux machine my load doesn't execeed 7mb with ~5k Sockets transfering data (single core). Maybe this information could help?

**Comment by tigranbs** [comment] 2016-07-15 10:35
I'm on a mac,
It's not depend on connections, it's just program initialization.
Even basic TCP Echo server getting around 3mb of memory without any connections.

It's not a memory leak, because even on 100K connection load memory not getting bigger. 
I've just surprised why it's allocating that much memory at the beginning, and for my usecase it's really can be bigger on multi cpu servers.

**Comment by alexcrichton** [comment] 2016-07-15 16:05
@tigranbs thanks for the report! Could you share the code you're testing out as well? 

Right now mio doesn't allocate *that* much, but if you're using `EventLoop` then there are a few large-ish allocations:

* First, a [`Poll` is created](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/event_loop.rs#L111) which contains a [buffer of events](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/poll.rs#L58) which for epoll [allocate 1024 slots](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/sys/unix/epoll.rs#L140-L149) and on kqueue [allocate even more](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/sys/unix/kqueue.rs#L153-L166).
* Next, an event loop [allocates a sync channel](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/event_loop.rs#L120) with a default capacity of [4k slots](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/event_loop.rs#L31).
* Finally, a [`Timer`](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/event_loop.rs#L113-L117) is created [which creates a 64k slab](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/timer.rs#L128-L156) and a number of wheel entries as well

Perhaps one of those is causing the increase in memory usage? If you [use `Poll` directly](https://github.com/carllerche/mio/blob/c3069801da91ef6fe568a925a74f348b398c5726/src/poll.rs#L12-L49) then you can sidestep the sync channel and timer allocations (as you're then responsible for configuring/registering them). The `Events` allocation currently isn't configurable but https://github.com/carllerche/mio/pull/425 should help because then you'll be easily able to configure it separately from `Poll`.

So I think the first thing to try might be to use `Poll` rather than `EventLoop`, and if that doesn't work perhaps apply https://github.com/carllerche/mio/pull/425 manually, and tweak the size of the `Events` allocation and see if that works?

**Comment by hexsel** [comment] 2016-07-15 18:11
Could this be the start up thread stack?  I thought the thread stack was 2MB.  Does it get discarded after the event loop is set up?

**Comment by sateffen** [comment] 2016-07-15 20:28
Hmm, I don't think mio is the "problem" or consumer, it looks like it's rust itself. I've compiled this code:

```
fn main() {
    std::thread::sleep(std::time::Duration::new(60,0));
}
```

Which in my opinion does nothing special, and doesn't allocate too much memory as well, but top says:

>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND          
> 2839 ubuntu    20   0   18124   2252   2028 S   0.0  0.0   0:00.00 min-stack-size  

So this code above already consumes 2252KiB memory, which is nearly your complete mio thing, without mio. So this is no mio, but rust related thing.

**Comment by tigranbs** [comment] 2016-07-15 20:57
As an example I've tried to compile and test this example 
https://github.com/hjr3/mob/blob/multi-echo-blog-post/src/main.rs 
and it seems the same result.
I think @sateffen you are right, I'm having also same result using threads.

Will try to ask this question in Rust users community website, maybe it depends on version.
Thanks !

**Comment by hexsel** [comment] 2016-07-18 15:02
@tigranbs if (big if, apologies if I'm wrong) the problem is that each thread stack is about 2MB plus some overhead, doesn't it make sense that having 4 threads (3 extra threads, plus one for the main method) will use about 8MB+overhead?

**Comment by tigranbs** [comment] 2016-07-18 15:10
@hexsel Yes! I'm using multiple loops to use multiple cores in server side.
I've tested `libuv` is allocating `~200kb` memory for every loop, but MIO is allocating about `~2.3mb` for every loop. Even without additional threads it's too match.
But good thing is that memory is not growing, it's pretty stabile.

**Comment by sateffen** [comment] 2016-07-18 15:15
Results on my cloud9 machine:

```
fn main() {
    std::thread::spawn(||{
        std::thread::sleep(std::time::Duration::new(60, 0));
    });

    std::thread::sleep(std::time::Duration::new(60, 0));
}
```

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                              
    2208 ubuntu    20   0   22240   2364   2144 S   0.0  0.0   0:00.00 min-stack-size   

Pretty much the same as above (ofcause, again, build with --release).

Hmhmhmhmhmhmhm. I don't know too much about the codebase, but there are some slabs that get aquired ahead of time, they could sum up (just as @alexcrichton spotted out earlier).

**Comment by tigranbs** [comment] 2016-07-18 15:26
That's right, I should definitely follow @alexcrichton instruction.
For server side software it's fine I can make a configurable number of loops/threads, but on mobile or other ARM devices it's huge amount of memory just for TCP communication.
Will share some information about results next week.
Thanks

**Comment by carllerche** [comment] 2016-07-19 20:26
Ok, with the changes that just landed on master, you should be able to use `Poll` yourself and allocate an `Events` instance of a custom capacity. I'm going to close this for now. If it still doesn't work out for you, please open a new issue & reference this.

**Closed by carllerche** 2016-07-19 20:26 UTC

**Comment by tigranbs** [comment] 2016-08-27 17:08
@alexcrichton I completed doing other parts of application, now I'm trying to make some optimizations.
Thanks for changing code, so that now I can change allocation sizes. But I'm trying to understand what numbers to put. What would be a best feat ?
Can you please give some information why you did this allocations by default ? is there anything that makes it "best practice" ?
**from your answer**
<ul>
<li>First, a Poll is created which contains a buffer of events which for epoll allocate 1024 slots and on kqueue allocate even more.
<li>Next, an event loop allocates a sync channel with a default capacity of 4k slots.
<li>Finally, a Timer is created which creates a 64k slab and a number of wheel entries as well
</ul>

Thanks

**Comment by alexcrichton** [comment] 2016-08-27 19:46
@tigranbs I think those numbers were mostly just pulled out of a hat, I'd recommend some testing locally to figure out the best numbers which fit your applications need. Each number reflects various performance characteristics, but it depends mostly on the task at hand as to which would be appropriate.

**Comment by tigranbs** [comment] 2016-08-28 07:37
ok cool, thanks will try to figure out.
Also just a quick question (maybe not related to this topic), is it thread safe to accept connection in one EventLoop, read some data and then register that connection to another Thread EventLoop for getting events there ?
I'm thinking of `Yes it is thread safe`, but wanted to know exactly

**Comment by alexcrichton** [comment] 2016-08-28 17:58
Yes I believe it should be safe so long as one I/O object is only ever bound to at most one event loop for its entire lifetime

**Comment by carllerche** [comment] 2016-08-28 20:01
Sending an accepted socket to a different thread & `Poll` is safe, however you are not able to read data from the socket until you register it w/ a `Poll`.
