### ISSUE TITLE
Mio TcpStreams are not closed

### ISSUE THREAD

**Issue by sateffen** [carllerche/mio#415] opened 2016-06-24 20:01 UTC
Hey,

in my simple learning project [here](https://github.com/sateffen/rust-tcp-server) I wrote a simple echo server, which does nothing else. I read some examples, and this is pretty close to [this](https://github.com/hjr3/mob/blob/multi-echo-blog-post/src/main.rs) example. The example is for mio 0.4, but I ported it to 0.5, and it's working, but sockets are not closed correctly, and I don't know why.

I added a little nodejs test file, which creates 10k connections, writes a simple string to the connection, waits for the answer and closes the connection. Node sends a FIN flag, and closes the connection half, so the server has to close the connection as well.

On my rust side I receive an *hup* event, so I delete the connection from my slab, deregisters it from the event_loop, and it goes out of scope (I tested implementing the drop trait for my Connection, and at least the connection goes out of scope).

But now, after executing the test.js a second time, without restarting the rust program, I start receiving "ERADINUSE" errors, which tell me my socket limit is used up. Using `netstat -a` tells me, that there are thousands of sockets open (at least half open), even after the node script has stopped.

Sooo... That tells me, my little rust server doesn't clean up the socket properly, but I can't see, what I'm doing wrong. The people in the rust_beginners IRC room suggested, that you (mio) don't implement the drop-trait, so this might be the problem. I don't get your implementation completly, but might this be a problem?

Another thing is, I tried to call `self.socket.shutdown(Shutdown::Both);` on my TcpStream after I received the hup event, and it tells me I can't shutdown the connection, because of code 10057 -> No connection established.

Can you guys help me, and explain to me, why the sockets are not cleaned up properly? Is this a bug with mio? Am I doing something wrong? I can't find anything in any other projects, that they do differently, so I don't know what to try anymore...

**Comment by alexcrichton** [comment] 2016-06-24 21:38
One good way to test out if this is mio specific or not is to write the same server but with threads and `std::net`. My guess is that this is not mio specific (I think I've seen this before elsewhere), but it'd be good to test out!

In general mio doesn't do anything special when closing a socket beyond ensuring that `close` is called on it, which is the same as the standard library.

**Comment by carllerche** [comment] 2016-06-24 21:52
If you run the rust program, kill the process, then run the node one, do you get the same error?

**Comment by sateffen** [comment] 2016-06-24 22:24
The sourcecode is all online, you can run it, or look into it (to see my horrible first steps :-D).

The node process won't do anything if there is no counterpart that echoes the data. But I wrote the server with nodejs (doing the same as rust), and the effect is the same.

I think there something fundamental wrong in my setup, or my understanding of the complete system...

**Comment by sateffen** [comment] 2016-06-24 23:28
I somehow don't think, that this is a mistake in mio.

Nodejs could be one problem, windows could be a problem, but now there is something even stranger:

```
use std::net::{TcpStream, Shutdown};
use std::io::Write;

fn main() {
    let mut buffer: Vec<u8> = Vec::new();

    for i in 0..128 {
        buffer.push(i);
    }

    println!("Starting");
    for _ in 0..10000 {
        let mut stream = TcpStream::connect("127.0.0.1:8888").unwrap();

        // ignore the Result
        stream.write(&buffer).unwrap();
        stream.shutdown(Shutdown::Both).unwrap();
    }
    println!("Finished");
}
```

I tried this code to setup 10k sockets, that get cleaned up by rust. I know, this is no good code, but it tells something interesting: `netstat -a` is pretty empty, no connections listed here. But even after this program stopped (so rust should close all the sockets, like documented [here](https://doc.rust-lang.org/std/net/struct.TcpStream.html)), but the slab is not cleaned anymore. So... No socket gets an hup event, and the tcp-echo-server doesn't recognize the closing connections anymore (even though I call shutdown explicitly).

Now I'm even more confused, and don't know what I should think. The node server gets the connections, but gets the close events as well.

Like I said: Slowly but surely I don't think, that mio is the problem. But I don't know what to do anymore. If you wanna help me, it would be great, but you don't have to. I'm happy about every hint.

**Comment by sateffen** [comment] 2016-06-25 00:24
Hmm, changing the test code to:

```
use std::net::{TcpStream, Shutdown};
use std::io::{Write, Read};

fn main() {
    let mut buffer: Vec<u8> = Vec::new();

    for i in 0..128 {
        buffer.push(i);
    }

    println!("Starting");
    for _ in 0..10000 {
        let mut stream = TcpStream::connect("127.0.0.1:8888").unwrap();

        // ignore the Result
        stream.write(&buffer).unwrap();
        stream.read(&mut [0;128]).unwrap();
        stream.shutdown(Shutdown::Both).unwrap();
    }
    println!("Finished");
}
```

causes the tcp echo server to close the connections (so the slab gets cleaned), but now the sockets stay opened like with node in `netstat -a`. Calling this code twice generates a panic! as well, just like in node. So the problem is not a node problem, it's located in Rust, or Windows.

Btw: If the client doesn't read what the server has sent but quit the connection, the server (with mio) never receive an error or hup event. This causes the server to never clean up. Is this a problem that mio could solve? Or is that a timing problem?

**Comment by carllerche** [comment] 2016-06-25 12:29
You are running this on windows? I could believe that there is a bug in the mio windows code around this as it is less mature than the *nix implementation. Are you able to see if this happens on Linux? Could you provide the node script so that I can try to reproduce?

**Comment by sateffen** [comment] 2016-06-25 13:18
Yep, I'm running this on windows 10. Currently I'm busy, but later the day I'll shift the complete setup to cloud9 or my ubuntu server (not sure yet).

In the repository [https://github.com/sateffen/rust-tcp-server](https://github.com/sateffen/rust-tcp-server) I've commited everything (except the rust client thing). The *server.js* does exactly the same as the rust server (creates even the same output, stores the sockets in a list and so on).

The *test.js* fires up connections very furiously, just as test. This is causing the troubles to happen. I know, that this is no real benchmark, but I want to compare the ressources needed and time for such a heavy thing.

And the rust code, well, is the rust code.

My versions:
:
* Windows 10
* Rust version: rustc 1.8.0 (db2939409 2016-04-11)
* Node version: v6.2.2

PS: Something interesting, I don't know if my implementation sucks realy that hard: In idle the rust code needs around 5-7mb ram (node ~7-17mb), but while running the test.js the rust code raises it's need to ~700mb (node ~60mb).

**Comment by sateffen** [comment] 2016-06-25 14:17
On linux this looks quite cool. I set up a cloud9 machine with rust 1.9, there I have to turn down the number of connections in *test.js* to 5000 because of the file limit, but I can execute the *test.js* as often as I like, and I don't have any problems there. On windows with 5000 connections I ran into trouble after the fourth execution, telling me EADDRINUSE again.

But: Even on the ubuntu machine, calling *netstat -a*, or *netstat -tanp* results in tons of this:

```
tcp        0      0 localhost:49852         localhost:8888          TIME_WAIT  
tcp        0      0 localhost:53602         localhost:8888          TIME_WAIT  
tcp        0      0 localhost:55182         localhost:8888          TIME_WAIT
```

There are hundreds/thousands of this entries there, but I can't reproduce the EADDRINUSE error on linux.

Super funny: On linux the complete process NEVER even scratches the 8mb ram. It's just fix at around 7.xmb. On windows with 5k connections *test.js* the memory goes to 320mb - 350mb.

So I think this is a windows specific problem. On linux I don't get any problems, not with node nor rust. On windows I get problems with node and rust.

My conclusion up til now:

1. The rust process soaks up a lot of memory on windows. 5k test -> 300-350mb, 10k test -> 600-700mb. On linux it doesn't matter, it's around 7mb.
2. On linux it doesn't matter if the opposing client reads the socket or not after I wrote my echo. I tried the code from my earlier posts, without the read, and all connections get closed just like I expected. The memory consumption doesn't go up as well.

So the problem is windows itself, and I guess the windows implementation has some problems, as it's pretty new.

**Comment by sateffen** [comment] 2016-06-25 14:44
I just found this image: [https://de.wikipedia.org/wiki/Transmission_Control_Protocol#/media/File:Tcp_verbindung.png](https://de.wikipedia.org/wiki/Transmission_Control_Protocol#/media/File:Tcp_verbindung.png) which tells me, that a TCP connection doesn't close immediately after a FIN flag is set, but waits a certain timeout. On windows the timeout is 240secs as far as I read, so that explains the *netstat -a* things, and the EADDRINUSE errors in windows.

I'm sorry that I didn't know that.. It's the first time I've run into that kind of problem. Is there a way to decrease this time_wait timeout?

But the problem with the memory consumption is not explainable with this.

**Comment by bluejekyll** [comment] 2016-06-27 17:33
Is this an SO_LINGER problem?

`SO_LINGER       linger on close if data present`
`SO_LINGER_SEC   linger on close if data present with timeout in seconds`

I imagine Windows has a similar option. Linger causes the TIME_WAIT stuff you're experiencing.

**Comment by sateffen** [comment] 2016-06-27 18:41
According to [microsofts documentation about *setsockopt*](https://msdn.microsoft.com/de-de/library/windows/desktop/ms740476(v=vs.85).aspx) this is an option, but there is no way to disable SO_LINGER in [net2](https://doc.rust-lang.org/net2-rs/net2/index.html).

The next mystery, explained as exepected behavior^^ Hmm, but how to change the behavior now? I think this is a topic for the net2 guys.

So the last problematic part is the high usage of memory on windows.

**Comment by alexcrichton** [comment] 2016-06-27 22:33
Ah yeah feel free to send a PR to net2 to support more options, PRs are of course always welcome!

As for memory usage, the Windows implementation has some more gymnastics in terms of buffer management, and that may account for the extra memory usage you're seeing here

**Comment by sateffen** [comment] 2016-06-28 20:31
Hmm, do you think, that this is optimizable? I don't get all the code, I'm pretty new to the lower levels. But I have trust in you. Libuv can do this, so you can do it as well. Hopefully I'll learn enough new stuff to actually understand how the internals work, and help out.

For net2 I looked in the sourcecode, and it looks quite straight forward, so I'll see, whether I can do it or not. Maybe there are more options, that could be added in the same PR, but I've to read more about the setsocketopt thing on different OSes.

Thanks for the help =)

**Comment by alexcrichton** [comment] 2016-07-01 17:30
Ah yeah this may be something that's worth doing by default (I'd have to read more into it though). It'd also probably be worth at the very least exposing this at the mio layer in an ergonomic interface if it's fixing problems for you.

**Comment by xitep** [comment] 2016-07-01 17:35
@sateffen accordig [this older post](http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html) it appears that setting `SO_REUSEADDR` could help you as well. haven't tried. just an idea.

**Comment by bluejekyll** [comment] 2016-07-01 21:38
SO_REUSEADDR is oriented toward the ability to have a socket reuse the same port/address that is already in use by some other process/file-descriptor.

In this case, the discussion is specifically about the time it takes for sockets to shutdown, which is determined by SO_LINGER options. If, on the other hand, what you want is for all connections to go through their full transaction and properly terminate, then SO_LINGER is not what you want, and then you do want SO_REUSEADDR, because that will allow you to open a new socket after restarting a process but all of the TIME_WAIT connections are still around trying to cleanup the connections.

It all depends on your use case, though to be fair, I've often used both of these options together in servers where they are dealing with a lot of connections (most of my experience is Linux/Unix, not Windows, fwiw).

**Comment by sateffen** [comment] 2016-07-18 14:19
All in all, the SO_LINGER option is now available via net2, so this should be accessable in mio as well, if the net2 package is new enougth.

The only problem in this thread, that is still open, is the huge memory consumption. Should we create a new issue for the huge memory consumption, or do you guys want to track it in this ticket @alexcrichton  @carllerche ?

Do you need anything else for tracking down the problem? If I've got some free time the next days I'd like to help out, but I'm honest: The mio internals are not that simple to get^^

**Comment by alexcrichton** [comment] 2016-07-18 18:21
@sateffen I'd recommend opening a new issue targeted at that, thanks again for the investigation!

**Closed** 2016-07-19 10:28 UTC
