### ISSUE TITLE
Token/Handler based event loop does not compose well

### ISSUE THREAD

**Issue by sdroege** [carllerche/mio#173] opened 2015-05-18 06:54 UTC
While the current API with Tokens to distinguish event sources and a single handler works well for applications, I don't think it composes well if used libraries, especially due to the static tokens and single handler per event loop.

I think a system like the GLib event loop works better in that regard, where you have an abstraction over event sources (GSource) that is not strictly tied to file descriptors (but can be), then attach those event sources to the event loop and register handlers/callbacks to the event source (not the event loop).

This allows you to
a) get rid of the readable/writable/message/timeout specialization on the handlers and event sources (the specific event source defines what it is that is waking it up, while the event loop only provides the machinery for allowing it to do that by e.g. adding a file descriptor to a fdset or just asynchronously waking it up). This opens up the possibility for many more different kinds of event sources.
b) allow libraries to add their own event sources to some event loop, and be able to handle events from them without the application being involved anywhere except for running that event loop.

Note that GLib also distinguishes between an event loop (GMainLoop) and its context (GMainContext), the former just being something to iterate the context while the context itself keeps track of all the event sources and allows polling them. That way you only usually pass around the context to libraries, and have the loop itself hidden away from them. Also it is possible to define a thread-default event context (via a push/pop mechanism on thread local storage), which then makes it unnecessary to explicitly pass around the context.

I'm not necessarily saying that the GLib model is the best solution to these problems, but it worked well in the past, composes better and is more generic.

For some more background see:
https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html
https://tecnocode.co.uk/2014/03/27/what-is-gmaincontext/
https://tecnocode.co.uk/2015/05/05/a-detailed-look-at-gsource/

**Comment by rrichardson** [comment] 2015-05-18 12:12
This is an interesting idea, maybe not for mio but a thin wrapper around
mio. I haven't looked too closely at the code but iirc the loop handles the
different context types and resource types by using void pointers for
attachments and casting to structs that it and the user expect to exist.

How do you envision what this would look like with type and reference
safety in Rust?

**Comment by rrichardson** [comment] 2015-05-18 12:42
There is a significant limitation in Rust that makes this difficult, and
that is that there is no concept of a raw function pointer. There are only
closures where each is it's own type that implements the Fn* traits.

If such a raw fn pointer existed, this would be fairly trivial.  You could
supply a callback for each FD that you register with no additional runtime
overhead.

There is a way to do this if you treat each callback as a c style
function,  I personally would be for this being the lowest layer of mio,
with the Handler trait going a layer above which would be called by a
default callback if the user chose.

There is an example of how to trampoline from a c callback to a handler
trait in nathan7's http-parser (a wrapper around the joyent http lib)

**Comment by sdroege** [comment] 2015-05-18 13:33
That's a good point, not sure how to actually express a model like this with Rust's type system. It would be a much more generically useful API though, and I would expect similar needs in other areas too (UI toolkits maybe?).

**Comment by sdroege** [comment] 2015-05-18 21:14
You should be able to have a trait for an event source like GLib's GSource, which additionally has a dispatch() method. And each specific type that implements the event source trait could have a set_callback() method with a specific callback type, which would then be called with whatever parameters required by the dispatch() method implementation.

**Comment by carllerche** [comment] 2015-05-18 21:37
What API would you suggest? I believe the problem is that if the event loop takes ownership of any memory, it will not be able to free it appropriately. For example, if a socket is closed explicitly, the event loop is never notified, so if the event loop owns any memory at that point, it will not get released.

**Comment by rrichardson** [comment] 2015-05-18 21:51
When taking the library approach, a register(my_external_evented, readable,
edge, my_callback) -> token would have a counterpart
deregister(my_external_evented (or token))  so if someone explicitly
closes, they're also responsible to explicitly deregister.

Mio could also take advantage of an IO management layer that offers
functions such as connect and listen and close which
auto-registers/deregisters with the event_loop.
The challenge of doing that, though, is that reference ownership of the
event_loop and mutable members of the connection containers gets tricky.
(RefCell time :) )

**Comment by sdroege** [comment] 2015-05-19 14:06
I think the event source would own the socket (or whatever else triggers the events), and deregistering the event source (i.e. event source is owned by the event loop) from the event loop would destroy the event source (and thus its socket). So closing the socket goes together with removing it from the event loop.

**Comment by rrichardson** [comment] 2015-05-19 14:14
You'd need to notify the event source to close the socket, though, which
might be fine, this means that the "business logic" needs a handle to the
event manager.. it's possible..

I have been writing, and re-writing (and re-writing)  an API that wraps mio
and provides the functionality you're talking about.   Let me know if this
makes sense:

What I've settled on is a Context trait which contains a means of
extracting an Evented trait and also a callback,  This gets registered into
the reactor event loop.

The context being a trait makes it rather flexible, it could just be a
callback container, or a big chunk of business logic, up to you.  I have
the prelim write-up here:
https://github.com/rrichardson/reactor
the context trait:
https://github.com/rrichardson/reactor/blob/master/src/context.rs

and assorted functionality which will eventually coalesce into reactor:
https://github.com/rrichardson/reactor/blob/master/src/reactor.rs

I guess I'm looking for feedback, here.  In this model, the user would call
 reactor.close(mycontext) which would close the context.  They could also
call reactor.deregister(mycontext) which would remove it from the reactor
(literally move it out of the reactor and into the calling scope) but not
close the resources.

**Comment by carllerche** [comment] 2015-08-25 23:31
I'm going to close this as I don't think that there is currently anything actionable. It will probably be worth creating a new issue if this evolves.

**Closed by carllerche** 2015-08-25 23:31 UTC
