### ISSUE TITLE
Fork mio 0.5

### ISSUE THREAD

**Issue by thijsc** [carllerche/mio#732] opened 2017-09-21 08:14 UTC
We are still users of mio 0.5 in our monitoring agent. It does exactly what we need, we use all it's features such as unix sockets, notifications and timers. I've been looking into how to upgrade to 0.6. I see two options:

- We could move to Tokyo and see if we can find replacements for the missing features and/or write a crate for this ourselves.
- We could fork mio 0.5 and maintain it ourselves from now on.

I'm not sure yet which is the better path forward for us. How do you feel about the fork? Would be ok with using a name like `mio-classic` for the crate or should we come up with a new name?

**Comment by carllerche** [comment] 2017-09-21 16:44
All the deprecated features of mio can be supported out of crate. I moved them out here: github.com/carllerche/mio-more.

The best path forward would be for you to maintain `mio-more` until you can move to Tokio.

**Comment by carllerche** [comment] 2017-09-21 16:45
unix sockets are here: https://github.com/alexcrichton/mio-uds

**Comment by thijsc** [comment] 2017-09-22 08:54
I wasn't aware of `mio-more`, will check that out.

**Comment by carllerche** [comment] 2017-09-22 16:15
It isn't really maintained, but it shows that demos that everything that was removed from Mio can exist out of crate (which is why it was removed in the first place).

**Comment by carllerche** [comment] 2017-09-22 16:16
I'm going to close the issue. Feel free to re-open if you believe the issue is not addressed.

**Closed by carllerche** 2017-09-22 16:16 UTC
